platform:
  - x86
  - x64
environment:
  OPENSSL_LIBS: ssleay32:libeay32
  matrix:
    - RUST_VERSION: stable
      TARGET: msvc
    - RUST_VERSION: stable
      TARGET: gnu
    - RUST_VERSION: beta
      TARGET: msvc
    - RUST_VERSION: beta
      TARGET: gnu
    - RUST_VERSION: nightly
      TARGET: msvc
    - RUST_VERSION: nightly
      TARGET: gnu
matrix:
  allow_failures:
    - TARGET: msvc
      platform: x86
    - RUST_VERSION: nightly
cache:
  - target\debug\build
  - target\debug\deps
  - '%USERPROFILE%\.cargo'
install:
  - ps: |
        $env:PATH += ";${env:USERPROFILE}\.cargo\bin";
        if ($env:platform -eq 'x86') {
          $env:RUST_ARCH = "i686-pc-windows-${env:TARGET}";
          $env:ARCH = "x86";
          $env:bits = "32";
        } else {
          $env:RUST_ARCH = "x86_64-pc-windows-${env:TARGET}";
          $env:ARCH = "amd64";
          $env:bits ="64";
        }
        $env:OPENSSL_INCLUDE_DIR = "C:\OpenSSL-Win${env:bits}\include";
        $env:OPENSSL_LIB_DIR = "C:\OpenSSL-Win${env:bits}\lib";
        if ($env:TARGET -eq 'gnu') {
          $env:PATH += ";C:\msys64\mingw${env:bits}\bin";
          gcc --version;
        }
  - appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init.exe --default-host %RUST_ARCH% --default-toolchain %RUST_VERSION -y
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo build
