sudo: false
dist: trusty
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # needed for --verify

os:
  - linux
  - osx

cache:
- cargo: true

rust:
  - nightly
  - beta
  - stable

before_script: ci/before_script.sh
script: ci/script.sh

matrix:
  allow_failures:
    - rust: nightly
