[alias]
cargo-machete = "ubi:bnjbvr/cargo-machete"

[tools]
actionlint = "latest"
python = "3.13"
ruff = "latest"
rust = "stable"
uv = "latest"

[task_config]
includes = [
  ".tasks/_default.toml",
  ".tasks/python.toml",
  ".tasks/rust.toml",
  ".tasks/toml.toml",
]
