[alias]
cargo-machete = "ubi:bnjbvr/cargo-machete"

[tools]
actionlint = "latest"
rust = "stable"

[tasks.lint]
description = "Lint project"
depends = ["lint:*"]

[tasks."lint:clippy"]
description = "Lints Rust files with Clippy"
run = "cargo clippy --all-features --all-targets --workspace"

[tasks."lint:rust-unused-deps"]
tools.cargo-machete = "latest"
description = "Checks if there are any unused crate dependencies declared"
run = "cargo machete"

[tasks."lint:rustfmt"]
description = "Checks if Rust files are formatted correctly"
run = "cargo fmt --all --check"

[tasks."lint:taplo"]
tools.taplo = "latest"
description = "Lints TOML files with Taplo"
run = "taplo lint"

[tasks."lint:taplo-format"]
tools.taplo = "latest"
description = "Checks if TOML files are formatted correctly"
run = "taplo format --check --diff"
