#:schema https://mise.jdx.dev/schema/mise-task.json

[lint]
description = "Lint project"
depends = ["lint:*"]

["lint:clippy"]
description = "Lints Rust files with Clippy"
run = "cargo clippy --all-features --all-targets --workspace"

["lint:rust-unused-deps"]
tools.cargo-machete = "latest"
description = "Checks if there are any unused crate dependencies declared"
run = "cargo machete"

["lint:rustfmt"]
description = "Checks if Rust files are formatted correctly"
run = "cargo fmt --all --check"

["lint:taplo"]
tools.taplo = "latest"
description = "Lints TOML files with Taplo"
run = "taplo lint"

["lint:taplo-format"]
tools.taplo = "latest"
description = "Checks if TOML files are formatted correctly"
run = "taplo format --check --diff"
